cheatAreas = {
	{"AR0011", "Candlekeep Dream 1 (Do you remember Candlekeep?)"},
	{"AR0012", "Candlekeep Library (Main Door Trigger)"},
	{"AR0013", "Candlekeep Library (Stairway Triggers Up and Down)"},
	{"AR0014", "Candlekeep Library (Stairway Trigger Down)"},
	{"AR0020", "City Gates"},
	{"AR0021", "Crooked Crane 1st Floor"},
	{"AR0022", "Crooked Crane 2nd Floor"},
	{"AR0028", "Candlekeep Dream (After PC Soultheft)"},
	{"AR0041", "Random Encounter City"},
	{"AR0042", "Random Encounter Outdoor"},
	{"AR0043", "Random Encounter Outdoor (With rocks)"},
	{"AR0044", "Random Encounter Outdoor (sand)"},
	{"AR0045", "Random Encounter City"},
	{"AR0046", "Random Encounter City (bridge)"},
	{"AR0060", "Empty (Triggers, Doors... are there but no area)"},
	{"AR0061", "Empty (Triggers, Doors... are there but no area)"},
	{"AR0062", "Empty (Triggers, Doors... are there but no area)"},
	{"AR0063", "Empty (Triggers, Doors... are there but no area)"},
	{"AR0064", "Empty (Triggers, Doors... are there but no area)"},
	{"AR0065", "Empty (Triggers, Doors... are there but no area)"},
	{"AR0069", "Government Building (Cowled Cutscene -- 'Why is this man not gagged?')"},
	{"AR0070", "Spellhold (Irenicus Cutscene -- 'I cannot be caged...')"},
	{"AR0071", "Spellhold (Imoen Soultheft Cutscene -- 'Silence do, you have no purpose...')"},
	{"AR0072", "Ust Natha Temple (Irenicus/Bodhi, Ardula/Phaere Cutscene)"},
	{"AR0082", "Lich Grave in Bridge District Inn"},
	{"AR0083", "Candlekeep Library (Dream: PC learns to control the Slayer)"},
	{"AR0084", "Candlekeep Library (Stairway trigger down)"},
	{"AR0085", "Tree of Life"},
	{"AR0086", "Wooded Area"},
	{"AR0087", "Elven Dining Room"},
	{"AR0201", "Leading to ghoul village and beholder lair (Temple District)"},
	{"AR0202", "The Unseeing Eye Cult Hideout"},
	{"AR0203", "Temple of the Forgotten God -- Amaunator (Unseeing Eye Plot)"},
	{"AR0204", "The Forgotten Believers -- Temple City (Unseeing Eye Plot)"},
	{"AR0205", "The Beholder Hideout (Unseeing Eye Plot)"},
	{"AR0206", "Ghoul village (Temple District)"},
	{"AR0300", "The Docks"},
	{"AR0301", "Mae'Var's Hide Out"},
	{"AR0302", "Mae'Var's Inn 1st Floor -- Entrance"},
	{"AR0303", "Mae'Var's Inn 2nd Floor -- Training Area"},
	{"AR0304", "Mae'Var's Inn 3rd Floor -- Edwin"},
	{"AR0305", "Shadow Thieves Guild Entrance"},
	{"AR0306", "Renal Bloodscalp's Hideout"},
	{"AR0307", "Aran Linvail's Hideout"},
	{"AR0308", "Harper's 1st Floor"},
	{"AR0309", "Harper's 2nd Floor"},
	{"AR0310", "Pirates' Hideout in Sea Bounty Tavern"},
	{"AR0311", "Living Room (Entry points outside and up) -- Gaelan?"},
	{"AR0312", "Sleeping Room (Entry point down) -- Arledrian"},
	{"AR0313", "Sea Bounty Tavern 1st Floor"},
	{"AR0314", "Sea Bounty Tavern 2nd Floor"},
	{"AR0315", "Living Room (Favour for Edwin -- Mae'Var Plot)"},
	{"AR0316", "Sleeping Room (Favour for Edwin -- Mae'Var Plot)"},
	{"AR0317", "Sleeping Room (Favour for Edwin -- Mae'Var Plot)"},
	{"AR0318", "Storage Room"},
	{"AR0319", "Temple of Oghma"},
	{"AR0321", "Thief Stronghold (Hideout)"},
	{"AR0322", "Thief Stronghold (1st Floor)"},
	{"AR0323", "Thief Stronghold (2nd Floor)"},
	{"AR0324", "Thief Stronghold (3rd Floor)"},
	{"AR0325", "Corthala House 1st Floor"},
	{"AR0326", "Corthala House 2nd Floor"},
	{"AR0327", "Shadow Thief Entrance (sided with Bodhi)"},
	{"AR0328", "Shadow Thief 1st Floor (sided with Bodhi)"},
	{"AR0329", "Aran's Hideout (sided with Bodhi)"},
	{"AR0330", "House 1st Floor (Kangaxx)"},
	{"AR0331", "House Cellar (Kangaxx)"},
	{"AR0332", "Barracks in the Docks"},
	{"AR0333", "Barracks in the Docks"},
	{"AR0334", "Cromwell's Shop"},
	{"AR0335", "Sleeping Room"},
	{"AR0400", "Slums"},
	{"AR0401", "Jansen Cellar"},
	{"AR0402", "Jansen 1st Floor"},
	{"AR0403", "Jansen 2nd Floor"},
	{"AR0404", "Sewers beneath Coronet -- Lilarcor"},
	{"AR0405", "Slaver's Ship Building"},
	{"AR0406", "Copper Coronet"},
	{"AR0407", "Prebek's House"},
	{"AR0408", "Temple of Ilmater"},
	{"AR0409", "Living Room (Ployer's home)"},
	{"AR0410", "Sphere: Navigator's room -- Lavok's Hideout"},
	{"AR0411", "Sphere: Entrance floor"},
	{"AR0412", "Sphere: Ice and Fire Room"},
	{"AR0413", "Sphere: Enginge Room"},
	{"AR0414", "Sphere: Demon Plane"},
	{"AR0415", "Living Room 1st Floor"},
	{"AR0416", "Living Room 2nd Floor"},
	{"AR0417", "Living Room"},
	{"AR0418", "Myconids"},
	{"AR0419", "Myconid"},
	{"AR0420", "Sphere: Lizardmen Hideout"},
	{"AR0500", "Bridge District"},
	{"AR0501", "Tanner's Hideout 1st Floor"},
	{"AR0502", "Tanner's Hideout Cellar"},
	{"AR0503", "Tanner's Hideout Dock"},
	{"AR0504", "Saerk's House 1st Floor"},
	{"AR0505", "Saerk's House 2nd Floor"},
	{"AR0506", "Noble House 1st Floor"},
	{"AR0507", "Kidnappers' Hideout 1st Floor"},
	{"AR0508", "Kidnappers' Hideout 2nd Floor"},
	{"AR0509", "Five Flagons Inn 1st Floor"},
	{"AR0510", "Five Flagons Inn Theater"},
	{"AR0511", "Five Flagons Inn 2nd Floor"},
	{"AR0512", "Temple of Helm"},
	{"AR0513", "Calbor's Inn at Bridge District 1st Floor"},
	{"AR0514", "Inn at Bridge District 2nd Floor"},
	{"AR0515", "Inn at Bridge District 3rd Floor"},
	{"AR0516", "Planar Prison"},
	{"AR0517", "Planar Prison Cell"},
	{"AR0518", "Planar Prison Cell"},
	{"AR0519", "Planar Prison Cell"},
	{"AR0520", "Planar Prison Cell"},
	{"AR0521", "Planar Prison Cell"},
	{"AR0522", "Five Flagons Inn (Stronghold)"},
	{"AR0523", "Five Flagons Theater (Stronghold)"},
	{"AR0525", "House 1st Floor"},
	{"AR0526", "Sarcophagus Cellar"},
	{"AR0527", "House 1st Floor"},
	{"AR0528", "House 2nd Floor"},
	{"AR0529", "Neb's Hideout"},
	{"AR0530", "Storehouse"},
	{"AR0531", "Commoner House"},
	{"AR0600", "Circus Tent (phased)"},
	{"AR0601", "Air Plane in Irenicus's Dungeon"},
	{"AR0602", "Irenicus's Dungeon 1st Floor"},
	{"AR0603", "Irenicus's Dungeon 2nd Floor"},
	{"AR0604", "Circus Tent 1st Floor"},
	{"AR0605", "Circus Tent 2nd Floor"},
	{"AR0606", "Circus Tent 3rd Floor"},
	{"AR0607", "Circus Tent restored"},
	{"AR0700", "Waukeen's Promenade"},
	{"AR0701", "The Sewers"},
	{"AR0702", "Adventurer's Mart"},
	{"AR0703", "Temple of Ilmater"},
	{"AR0704", "Mithrest Inn"},
	{"AR0705", "Mekrath's Hideout in the Sewers (Haer'Dalis Plot)"},
	{"AR0706", "Armourer/Fletcher"},
	{"AR0707", "Enge's Shop"},
	{"AR0708", "Cernd's former home"},
	{"AR0709", "Den of the Seven Vales 1st Floor"},
	{"AR0710", "Fennecia's Home"},
	{"AR0711", "Illithid Hideout in the Sewers (The Hidden Plot)"},
	{"AR0712", "Den of the Seven Vales 2nd Floor"},
	{"AR0713", "Store or Inn at Promenade"},
	{"AR0714", "Debris at Waukeen's Promenade (Irenicus Cutscene in the beginning)"},
	{"AR0800", "Graveyard"},
	{"AR0801", "Bodhi's Hideout (sided with Aran)"},
	{"AR0802", "Netherscroll, Korgan's Book, Edwin"},
	{"AR0803", "Bodhi's Lair (sided with Aran)"},
	{"AR0804", "Pai'Na's Hideout"},
	{"AR0805", "Crypt"},
	{"AR0806", "Crypt"},
	{"AR0807", "Crypt"},
	{"AR0808", "Bodhi's Hideout (Abduction Plot, getting Imoen's soul)"},
	{"AR0809", "Bodhi's Lair (Abduction Plot, getting Imoen's soul)"},
	{"AR0810", "Crypt"},
	{"AR0811", "Crypt"},
	{"AR0812", "Crypt"},
	{"AR0813", "Crypt"},
	{"AR0900", "Temple District"},
	{"AR0901", "Temple of Helm"},
	{"AR0902", "Temple of Lathander"},
	{"AR0903", "Order of the Radiant Heart"},
	{"AR0904", "Temple of Talos"},
	{"AR0905", "Pimlico's Estate"},
	{"AR0906", "Guarded Compound 1st Floor"},
	{"AR0907", "Guarded Compound 2nd Floor"},
	{"AR1000", "Government District"},
	{"AR1001", "Delryn's Estate"},
	{"AR1002", "Councel Building"},
	{"AR1003", "Firecam's Estate"},
	{"AR1004", "Deril's Estate (Cernd Plot)"},
	{"AR1005", "Prison"},
	{"AR1006", "Jysstev's Estate (Oisig Plot)"},
	{"AR1007", "Noble House"},
	{"AR1008", "Twisted Rune"},
	{"AR1009", "Noble House (Isaea Roenall's)"},
	{"AR1010", "Temple of Waukeen"},
	{"AR1100", "Umar Hills"},
	{"AR1101", "Valygar's Cabin"},
	{"AR1102", "Merella's Cabin"},
	{"AR1103", "Jermien's Cabin"},
	{"AR1104", "Mayor Lloyd's Cabin"},
	{"AR1105", "Imnesvale Inn"},
	{"AR1106", "Umar's Cave"},
	{"AR1107", "Ranger-Protector's Cabin (Stronghold)"},
	{"AR1200", "Windspear Hills"},
	{"AR1201", "Firkraag's Entrance"},
	{"AR1202", "Firkraag's Maze"},
	{"AR1203", "Firkraag's Hideout"},
	{"AR1204", "Garren Windspear's Cabin"},
	{"AR1300", "De'Arnise Keep Destroyed"},
	{"AR1301", "De'Arnise Cellar"},
	{"AR1302", "De'Arnise Keep 1st Floor"},
	{"AR1303", "De'Arnise Keep 2nd Floor (Destroyed)"},
	{"AR1304", "De'Arnise Keep (Restored, Stronghold)"},
	{"AR1305", "De'Arnise Keep (Stronghold)"},
	{"AR1306", "De'Arnise Keep (Stronghold)"},
	{"AR1307", "De'Arnise Keep (Stronghold)"},
	{"AR1400", "Shadow Temple Land (restored, Ranger)"},
	{"AR1401", "Shadow Temple"},
	{"AR1402", "Shadow Dragon Hideout"},
	{"AR1403", "Wolfwere Hideout"},
	{"AR1404", "Shadow Temple Land shadowed"},
	{"AR1500", "Spellhold"},
	{"AR1501", "Cave (Spellhold Test)"},
	{"AR1502", "Fire Room (Spellhold Test)"},
	{"AR1503", "Spore Room (Spellhold Test)"},
	{"AR1504", "Crushing Trap Room (Spellhold Test)"},
	{"AR1505", "Lever Room (Spellhold Test)"},
	{"AR1506", "Troll Cave (Spellhold Test)"},
	{"AR1507", "Kobold Room (Spellhold Test)"},
	{"AR1508", "Final Judgement Spellhold Test"},
	{"AR1509", "Myconid Room (Spellhold Test)"},
	{"AR1510", "Sahuagin Room (Spellhold Test)"},
	{"AR1511", "Elven Table while Spellhold Test"},
	{"AR1512", "Bodhi's Hunt Level 1"},
	{"AR1513", "Bodhi's Hunt Level 2"},
	{"AR1514", "Bodhi's Hunt Level 3 (1st Slayer Change Happens here)"},
	{"AR1515", "Spellhold (Irenicus's Living Room)"},
	{"AR1516", "Spellhold (Soultheft Level)"},
	{"AR1600", "Brynnlaw"},
	{"AR1601", "Desharik's Estate"},
	{"AR1602", "Brynnlaw's Inn"},
	{"AR1603", "Brynnlaw's Shop"},
	{"AR1604", "Temple of Umberlee"},
	{"AR1605", "CW's House"},
	{"AR1606", "House of Desharik's Lover"},
	{"AR1607", "Githyanki Assault"},
	{"AR1608", "Cellar of Brothel"},
	{"AR1609", "Courtesan Room"},
	{"AR1610", "Brothel Prison"},
	{"AR1611", "Brothel"},
	{"AR1612", "Brothel Kitchen"},
	{"AR1613", "Brothel HQ"},
	{"AR1700", "Small Teeth Pass"},
	{"AR1800", "North Forest"},
	{"AR1900", "Druid Grove Area"},
	{"AR1901", "Druid Grove"},
	{"AR1902", "Storehouse (Ihtafeer's Storehouse)"},
	{"AR1904", "Troll Hill"},
	{"AR1905", "Store Tower"},
	{"AR2000", "Trademeet"},
	{"AR2001", "The Smithy"},
	{"AR2002", "Fentan's House"},
	{"AR2006", "Tiri's Home"},
	{"AR2007", "High Merchant's Estate"},
	{"AR2008", "Temple of Waukeen"},
	{"AR2009", "High Merchant Prison"},
	{"AR2010", "Trademeet's Inn"},
	{"AR2011", "Alibakkar's Estate"},
	{"AR2012", "Lurraxol's Estate"},
	{"AR2013", "Trademeet Crypt"},
	{"AR2014", "Djinni's Tent"},
	{"AR2015", "Merchant Tent"},
	{"AR2016", "Raffee's Tent"},
	{"AR2017", "Courtesan Tent"},
	{"AR2018", "Tent (no exit)"},
	{"AR2100", "Underdark"},
	{"AR2101", "Beholder Cave in Underdark"},
	{"AR2102", "Adalon's Cave"},
	{"AR2200", "Ust Natha"},
	{"AR2201", "Temple in Ust Natha"},
	{"AR2202", "Inn in Ust Natha 1st Floor"},
	{"AR2203", "Inn in Ust Natha; 2nd Floor"},
	{"AR2204", "House in Ust Natha"},
	{"AR2205", "House in Ust Natha"},
	{"AR2206", "Qilue's House in Ust Natha"},
	{"AR2207", "Deirex's Tower in Ust Natha"},
	{"AR2208", "Jarlaxle's House wherever"},
	{"AR2209", "Jae'llat's House"},
	{"AR2210", "Deirex's Cave"},
	{"AR2300", "Sahuagin City"},
	{"AR2400", "Mind Flayers in Underdark"},
	{"AR2401", "Cave Between Underdark and Exit from Underdark"},
	{"AR2402", "Kuo Toa in Underdark"},
	{"AR2500", "Elven Temple at Underdark Exit"},
	{"AR2600", "Thetyr Wood"},
	{"AR2601", "Meet Drizzt Do'Urden"},
	{"AR2602", "Cave in Woods to Suldanessellar"},
	{"AR2603", "Coran's Cabin"},
	{"AR2700", "Ancient Spirits?"},
	{"AR2800", "Suldanessellar"},
	{"AR2801", "House of High Priestess of Suldanessellar"},
	{"AR2802", "House in Suldanessellar"},
	{"AR2803", "Rillifane Temple"},
	{"AR2804", "To the Tree of Life (Entrance Hidden)"},
	{"AR2805", "To the Tree of Life (Entrance Revealed)"},
	{"AR2806", "Tree of Life"},
	{"AR2807", "Black Dragon's Hideout"},
	{"AR2808", "House in Suldanessellar"},
	{"AR2809", "House in Suldanessellar - Puzzle Box"},
	{"AR2810", "House in Suldanessellar"},
	{"AR2811", "House in Suldanessellar"},
	{"AR2812", "Temple of Rillifane after the Battle"},
	{"AR2900", "The Abyss"},
	{"AR2901", "Fear (Abyss)"},
	{"AR2902", "Pride (Abyss)"},
	{"AR2903", "Greed (Abyss)"},
	{"AR2904", "Selfish (Abyss)"},
	{"AR2905", "Sarevok (Abyss)"},
	{"AR2906", "Jon Battle ?"},
	{"AR3000", "Watcher's Keep"},
	{"AR3001", "Watcher's Keep -- Altar level"},
	{"AR3003", "Watcher's Keep -- Compass level"},
	{"AR3004", "Watcher's Keep"},
	{"AR3005", "Watcher's Keep -- tieflings"},
	{"AR3006", "Watcher's Keep -- Succubus"},
	{"AR3007", "Watcher's Keep --Cambion"},
	{"AR3008", "Watcher's Keep -- Baalor (Paladin Sword)"},
	{"AR3009", "Watcher's Keep -- Wild Magic ?"},
	{"AR3010", "Watcher's Keep -- Tanar'ri -- Obelisk"},
	{"AR3011", "Watcher's Keep -- Bard's Gloves, Manman's Journal"},
	{"AR3012", "Watcher's Keep -- Tahazzar"},
	{"AR3013", "Watcher's Keep -- Ka'rashur"},
	{"AR3014", "Watcher's Keep -- White Dragon Scales"},
	{"AR3015", "Watcher's Keep -- Aesgareth"},
	{"AR3016", "Watcher's Keep -- Chromatic Demon; Elementalist Level"},
	{"AR3017", "Watcher's Keep -- Carston and the machine"},
	{"AR3018", "Watcher's Keep -- Saladrex (Dragon)"},
	{"AR3019", "Watcher's Keep -- Helmite Level -- Last Seals"},
	{"AR3020", "Watcher's Keep -- Imprisoned One"},
	{"AR3021", "Watcher's Keep -- Illithids"},
	{"AR3022", "Watcher's Keep -- Anti-Paladins"},
	{"AR3023", "Watcher's Keep -- 'Adventure Level' (Mini Map!!!)"},
	{"AR3024", "Watcher's Keep -- Dragon -- Fear Challenge"},
	{"AR3025", "Watcher's Keep -- Orcs -- Ixil's Nail"},
	{"AR3026", "Watcher's Keep -- Imp -- Game"},
	{"AR3027", "Watcher's Keep -- Crypt -- Demi-Lich"},
	{"OH4000", "Rasaad - The Amphitheater"},
	{"OH4010", "Rasaad - Tears of Selune battle encounter"},
	{"OH4100", "Rasaad - Dark Moon Heretic Temple"},
	{"OH4101", "Rasaad - Dark Moon Heretic Temple Interior"},
	{"OH5000", "Dorn - Radiant Heart (Wedding)"},
	{"OH5100", "Dorn - Resurrection Gorge"},
	{"OH5110", "Dorn - Resurrection Gorge Cave"},
	{"OH5120", "Dorn - Resurrection Gorge Tree Interior"},
	{"OH5200", "Dorn - Resurrection Gorge Interior"},
	{"OH5300", "Dorn - Helmite Camp"},
	{"OH6000", "Neera - The Wild Forest"},
	{"OH6010", "Neera - Random Encounter in Athkatla"},
	{"OH6100", "Neera - The Hidden Refuge"},
	{"OH6200", "Neera - The Hidden Refuge (Destroyed)"},
	{"OH6300", "Neera - Red Wizard Enclave"},
	{"OH7000", "Hexxat - Top Left Quarter (Dragomir)"},
	{"OH7100", "Hexxat - Bottom Left Quarter (Shou Lung)"},
	{"OH7200", "Hexxat - Bottom Right Quarter (Zakhara)"},
}
cheatAreasArena = {
	{"OH8000", "TBP2 - Suzail Tavern"},
	{"OH8100", "TBP2 - Staging Area Map"},
	{"OH8200", "TBP2 - Arena 1"},
	{"OH8300", "TBP2 - Arena 2"},
	{"OH8400", "TBP2 - Arena 3"},
}
cheatAreasTutorial = {
	{"AR0015", "Baldur's Gate Estate (Tutorial starts here)"},
	{"AR0016", "Baldur's Gate Estate (Tutorial area)"},
	{"AR0017", "Baldur's Gate Estate (Tutorial area)"},
	{"AR0018", "Baldur's Gate Estate Cellar (Tutorial area)"},
}
cheatAreasExpansion = {
	{"AR3000", "Watcher's Keep"},
	{"AR3001", "Watcher's Keep -- Altar level"},
	{"AR3003", "Watcher's Keep -- Compass level"},
	{"AR3004", "Watcher's Keep"},
	{"AR3005", "Watcher's Keep -- tieflings"},
	{"AR3006", "Watcher's Keep -- Succubus"},
	{"AR3007", "Watcher's Keep --Cambion"},
	{"AR3008", "Watcher's Keep -- Baalor (Paladin Sword)"},
	{"AR3009", "Watcher's Keep -- Wild Magic ?"},
	{"AR3010", "Watcher's Keep -- Tanar'ri -- Obelisk"},
	{"AR3011", "Watcher's Keep -- Bard's Gloves, Manman's Journal"},
	{"AR3012", "Watcher's Keep -- Tahazzar"},
	{"AR3013", "Watcher's Keep -- Ka'rashur"},
	{"AR3014", "Watcher's Keep -- White Dragon Scales"},
	{"AR3015", "Watcher's Keep -- Aesgareth"},
	{"AR3016", "Watcher's Keep -- Chromatic Demon; Elementalist Level"},
	{"AR3017", "Watcher's Keep -- Carston and the machine"},
	{"AR3018", "Watcher's Keep -- Saladrex (Dragon)"},
	{"AR3019", "Watcher's Keep -- Helmite Level -- Last Seals"},
	{"AR3020", "Watcher's Keep -- Imprisoned One"},
	{"AR3021", "Watcher's Keep -- Illithids"},
	{"AR3022", "Watcher's Keep -- Anti-Paladins"},
	{"AR3023", "Watcher's Keep -- 'Adventure Level' (Mini Map!!!)"},
	{"AR3024", "Watcher's Keep -- Dragon -- Fear Challenge"},
	{"AR3025", "Watcher's Keep -- Orcs -- Ixil's Nail"},
	{"AR3026", "Watcher's Keep -- Imp -- Game"},
	{"AR3027", "Watcher's Keep -- Crypt -- Demi-Lich"},
	{"AR4000", "Spirit Heads"},
	{"AR4500", "Pocket Plane"},
	{"AR5000", "Saradush"},
	{"AR5001", "Gromnir 1st Level"},
	{"AR5002", "Gromnir's Hideout"},
	{"AR5003", "Saradush Tavern (Tankard Tree)"},
	{"AR5004", "Temple of Waukeen"},
	{"AR5005", "Gromnir's Barracks"},
	{"AR5006", "Saradush Prison"},
	{"AR5007", "Basement Entrance to Gromnir's Hideout"},
	{"AR5008", "Kiser's Home"},
	{"AR5009", "House (no exit?)"},
	{"AR5010", "Countess Santele's Home"},
	{"AR5011", "Arcana Archives"},
	{"AR5012", "House"},
	{"AR5013", "Sewers beneath Saradush"},
	{"AR5014", "Kiser's Home -- Cellar"},
	{"AR5015", "Saradush Militia Entrance"},
	{"AR5016", "Saradush Castle Jail (Kiser Plot)"},
	{"AR5200", "Fire Giant Entrance Area"},
	{"AR5201", "Fire Giant Keep"},
	{"AR5202", "Nyalee's Hideout; Gorion Wraith"},
	{"AR5203", "Yaga-Shura's Camp"},
	{"AR5204", "Yaga-Shura's Keep"},
	{"AR5500", "Amkethran"},
	{"AR5501", "Amkethran Inn"},
	{"AR5502", "Kerrick the Smith's House"},
	{"AR5503", "Chyil's House"},
	{"AR5504", "Smuggler Cave"},
	{"AR5505", "Balthazar's Home"},
	{"AR5506", "Commoner's Home"},
	{"AR5507", "Empty Home"},
	{"AR5508", "Faheed's Home"},
	{"AR5509", "Amkethran Crypt"},
	{"AR6000", "Abazigal's Entrance"},
	{"AR6001", "Abazigal's Lair Entrance Hall"},
	{"AR6002", "Abazigal's Lair -- Cells"},
	{"AR6003", "Abazigal's Lair -- Iycanth the Mad, Bondari"},
	{"AR6004", "Abazigal's Lair -- Fll'Yissetat"},
	{"AR6005", "Abazigal's Hideout"},
	{"AR6008", "Frost Salamander Cave"},
	{"AR6011", "Orbs and Gauth"},
	{"AR6012", "Pool Home -- breath under water"},
	{"AR6100", "Area outside Sendai's Hideout"},
	{"AR6101", "Main Entrance Sendai's Lair"},
	{"AR6102", "Sendai's Lair -- Slavemaster"},
	{"AR6103", "Sendai's Lair -- Spiders"},
	{"AR6104", "Sendai's Lair -- Crossway"},
	{"AR6105", "Sendai's Lair -- Diaytha, Abishai"},
	{"AR6106", "Sendai's Lair -- Captain Egeissag"},
	{"AR6107", "Sendai's Lair -- Mithykyl"},
	{"AR6108", "Sendai's Lair -- Sendai"},
	{"AR6109", "Sendai's Lair -- Drow"},
	{"AR6110", "Sendai's Lair -- Odamaron"},
	{"AR6111", "Woodcutter's House -- Sendai's Area"},
	{"AR6200", "The Throne of Bhaal"},
	{"AR6300", "Oasis in Tethyr"},
	{"AR6400", "River Area"},
	{"OH4200", "Rasaad - Dwarven Clanhold Exterior"},
	{"OH4210", "Rasaad - Dwarven Clanhold Interior"},
	{"OH4220", "Rasaad - Dwarven Mines"},
	{"OH4230", "Rasaad - Plane of Shadow"},
	{"OH4290", "Rasaad - Sharran Ambush"},
	{"OH5400", "Dorn - Forest Clearing"},
	{"OH5500", "Dorn - Lunia"},
	{"OH6400", "Neera - Wilderness Clearing"},
	{"OH6450", "Neera - The Black Pits: Arena"},
	{"OH6460", "Neera - The Black Pits: Staging Area"},
	{"OH6500", "Neera - Thayan Estate"},
	{"OH7300", "Hexxat - Completed Maze (Korkorran)"},
	{"OH7310", "Hexxat - Scene with L"},
}