cheatAreas = {
	{"AR0002", "BG Temple de Helm (Baldur's Gate)"},
	{"AR0004", "BG Maison de Bheren, rez-de-chaussée (Baldur's Gate)"},
	{"AR0005", "BG Maison de Bheren, étage (Ange, le chat)"},
	{"AR0006", "BG Maison de Rinnie, rez-de-chaussée (Baldur's Gate)"},
	{"AR0007", "BG Maison de Rinnie, étage"},
	{"AR0008", "BG Generic home, ground floor"},
	{"AR0009", "BG Generic home, second floor"},
	{"AR0010", "BG Jardak's home, ground floor (Drelik the butler)"},
	{"AR0011", "BG Jardak's home, second floor"},
	{"AR0012", "BG Generic home, ground floor"},
	{"AR0013", "BG Generic home, second floor"},
	{"AR0014", "BG Generic home, ground floor"},
	{"AR0015", "BG Generic home, second floor"},
	{"AR0016", "BG Generic home, ground floor"},
	{"AR0017", "BG Generic home, second floor"},
	{"AR0018", "BG Generic home, ground floor"},
	{"AR0019", "BG Generic home, second floor"},
	{"AR0020", "BG Generic home, ground floor"},
	{"AR0021", "BG Generic home, second floor"},
	{"AR0100", "BG NW Baldur's Gate (Helm & Cloak, Silvershield Estate)"},
	{"AR0101", "BG Silvershield Estate, ground floor"},
	{"AR0102", "BG Silvershield Estate, second floor"},
	{"AR0103", "BG Splurging Sturgeon, ground floor (Lusselyn)"},
	{"AR0104", "BG Splurging Sturgeon, second floor (Mr. Shade)"},
	{"AR0105", "BG Blade and Stars, ground floor (G'axir the Seer, Elkart)"},
	{"AR0106", "BG Blade and Stars, second floor (Maple Willow Aspen)"},
	{"AR0107", "BG Blade and stars, third floor (Reginald Longtooth Worthington III)"},
	{"AR0108", "BG Duchal Palace, ground floor"},
	{"AR0109", "BG Duchal Palace, second floor"},
	{"AR0110", "BG Duchal Palace, third floor"},
	{"AR0111", "BG Duchal Palace, basement"},
	{"AR0112", "BG Undercellars (Slythe, Krystin)"},
	{"AR0114", "BG Blushing Mermaid, ground floor (Larze)"},
	{"AR0115", "BG Blushing Mermaid, second floor"},
	{"AR0116", "BG Helm & Cloak, ground floor (Gorpel Hind)"},
	{"AR0117", "BG Helm & Cloak, second floor front (Emissary Sarah)"},
	{"AR0118", "BG Helm & Cloak, second floor rear"},
	{"AR0119", "BG Three Old Kegs tavern, ground floor"},
	{"AR0120", "BG Three Old Kegs tavern, second floor (Skull of Keraph)"},
	{"AR0121", "BG Three Old Kegs tavern, third floor (Areana)"},
	{"AR0123", "BG Undercity (Temple of Bhaal, old city ruins)"},
	{"AR0125", "BG Temple of Bhaal (game finale)"},
	{"AR0126", "BG Ragefast's home"},
	{"AR0127", "BG Merchant League, ground floor (Irlentree)"},
	{"AR0128", "BG Merchant League, second floor (Aldeth, Brandilar, Zorl)"},
	{"AR0129", "BG Merchant League, third floor"},
	{"AR0130", "BG Hall of Wonders (Alora)"},
	{"AR0131", "BG Temple of Gond (Forthel August)"},
	{"AR0132", "BG Lady's House (Agnasia, Chanthalas Ulbright)"},
	{"AR0133", "BG Low Lantern, ground floor"},
	{"AR0134", "BG Low Lantern, first underwater level (Desreta, Vay-ya)"},
	{"AR0135", "BG Low Lantern, second underwater level (Yago)"},
	{"AR0136", "BG Low Lantern, third underwater level"},
	{"AR0137", "BG Ramazith's Tower, ground floor"},
	{"AR0138", "BG Ramazith's Tower, sixth (top) floor"},
	{"AR0139", "BG Ramazith's Tower, second floor"},
	{"AR0140", "BG Ramazith's Tower, third floor"},
	{"AR0141", "BG Ramazith's Tower, fourth floor"},
	{"AR0142", "BG Ramazith's Tower, fifth floor"},
	{"AR0143", "BG Oberan's Estate, ground floor"},
	{"AR0144", "BG Oberan's Estate, second floor"},
	{"AR0145", "BG Oberan's Estate, third floor (Helshara, Ithmeera, Delorna)"},
	{"AR0146", "BG Thieves Guild, Maze"},
	{"AR0148", "BG Thieves Guild, front house (fourth from west)"},
	{"AR0149", "BG Ilmater's Shrine"},
	{"AR0150", "BG Thieves Guild, front house (first from west)"},
	{"AR0151", "BG Thieves Guild, front house (second from west)"},
	{"AR0152", "BG Thieves Guild, front house (third from west)"},
	{"AR0153", "BG Thieves Guild, main area (Alatos, Narlen Darkwalk)"},
	{"AR0154", "BG Keexie Tavern, ground floor"},
	{"AR0155", "BG Generic home, ground floor"},
	{"AR0156", "BG Generic home, second floor"},
	{"AR0157", "BG Quinn's home, ground floor"},
	{"AR0158", "BG Quinn's home, second floor"},
	{"AR0159", "BG Generic home, ground floor"},
	{"AR0160", "BG Generic home, second floor"},
	{"AR0161", "BG Degrodel's home"},
	{"AR0162", "BG Louise and Laerta's home"},
	{"AR0163", "BG Generic home, ground floor"},
	{"AR0164", "BG Generic home, second floor"},
	{"AR0165", "BG Generic tavern, ground floor (Connoly Finn)"},
	{"AR0166", "BG Generic tavern, second floor (Borinole Mann)"},
	{"AR0167", "BG Phierkas's home, ground floor"},
	{"AR0168", "BG Phierkas's home, second floor"},
	{"AR0169", "BG Generic home, ground floor"},
	{"AR0170", "BG Generic home, second floor"},
	{"AR0171", "BG Keexie Tavern, second floor"},
	{"AR0200", "BG N Baldur's Gate (Ramazith's Tower, Duchal Palace)"},
	{"AR0224", "BG BG Sewers, western area (Schlumpsha the Sewer King)"},
	{"AR0225", "BG BG Sewers, central area (Ratchild)"},
	{"AR0226", "BG BG Sewers, eastern area (ogre mage for Scar)"},
	{"AR0300", "BG NE Baldur's Gate (Blushing Mermaid, Splurging Sturgeon, Counting House)"},
	{"AR0302", "BG Generic home, ground floor"},
	{"AR0303", "BG Generic home, second floor"},
	{"AR0304", "BG Generic store"},
	{"AR0305", "BG Generic home, ground floor"},
	{"AR0306", "BG Generic home, second floor"},
	{"AR0307", "BG Counting House, ground floor (Jacil or Ulf)"},
	{"AR0308", "BG Counting House, second floor (Captain Kieres)"},
	{"AR0400", "BG Farm NE of BG (Wenric, zombie farm)"},
	{"AR0401", "BG Wenric's farmhouse"},
	{"AR0500", "BG Durlag's Tower, exterior"},
	{"AR0501", "BG Durlag's Tower, first subterranean level"},
	{"AR0502", "BG Durlag's Tower, ground floor"},
	{"AR0503", "BG Durlag's Tower, second floor"},
	{"AR0504", "BG Durlag's Tower, third floor (Rigglio)"},
	{"AR0505", "BG Durlag's Tower, fourth floor (Kirinhale)"},
	{"AR0506", "BG Durlag's Tower, chessboard (fourth subterranean level)"},
	{"AR0507", "BG Durlag's Tower, cold elemental challenge (fourth subterranean level)"},
	{"AR0508", "BG Durlag's Tower, fire elemental challenge (fourth subterranean level)"},
	{"AR0509", "BG Durlag's Tower, air elemental challenge (fourth subterranean level)"},
	{"AR0510", "BG Durlag's Tower, earth elemental challenge (fourth subterranean level)"},
	{"AR0511", "BG Durlag's Tower, second subterranean level (Pride, Avarice, Love, Fear)"},
	{"AR0512", "BG Durlag's Tower, third subterranean level (Kiel, Islanne, door maze)"},
	{"AR0513", "BG Durlag's Tower, fourth subterranean level (leads to elemental challenges)"},
	{"AR0514", "BG Durlag's Tower, fifth subterranean level"},
	{"AR0515", "BG Durlag's Tower, stone golem question chamber"},
	{"AR0516", "BG Durlag's Tower, demon knight chamber (Dalton)"},
	{"AR0600", "BG W Baldur's Gate (Hall of Wonders, Lady's House, Ragefast's home)"},
	{"AR0601", "BG Seven Suns, ground floor"},
	{"AR0602", "BG Seven Suns, second floor"},
	{"AR0603", "BG Seven Suns, basement (Jhasso)"},
	{"AR0606", "BG Flaming Fist HQ, basement"},
	{"AR0607", "BG Flaming Fist HQ, ground floor"},
	{"AR0608", "BG Flaming Fist HQ, second floor (Duke Eltan)"},
	{"AR0609", "BG Temple of Umberlee (Jalantha Mistmyr)"},
	{"AR0611", "BG Iron Throne, basement"},
	{"AR0612", "BG Iron Throne, second floor (Dra'tan)"},
	{"AR0613", "BG Iron Throne, third floor (Nortuary, Emissary Tar)"},
	{"AR0614", "BG Iron Throne, fourth floor (Destus Gurn)"},
	{"AR0615", "BG Iron Throne, fifth (top) floor (chapter five finale)"},
	{"AR0616", "BG Iron Throne, ground floor (Triadore)"},
	{"AR0617", "BG Tremain Belde'ar's home, ground floor"},
	{"AR0618", "BG Tremain Belde'ar's home, second floor"},
	{"AR0619", "BG Fenten's Home, ground floor"},
	{"AR0620", "BG Fenten's Home, second floor"},
	{"AR0621", "BG Iron Throne, roof"},
	{"AR0700", "BG Central Baldur's Gate (marketplace, Oberan's home)"},
	{"AR0702", "BG Harbormaster's building"},
	{"AR0703", "BG Sorcerous Sundries, ground floor (Halbazzer Drin)"},
	{"AR0704", "BG Sorcerous Sundries, second floor"},
	{"AR0705", "BG Elfsong Tavern, ground floor (Brevlik)"},
	{"AR0706", "BG Elfsong Tavern, second floor (Alyth, Cyrdemac)"},
	{"AR0707", "BG Generic home, ground floor"},
	{"AR0708", "BG Generic home, second floor"},
	{"AR0709", "BG Generic home, ground floor"},
	{"AR0710", "BG Generic home, second floor"},
	{"AR0711", "BG Generic home, ground floor"},
	{"AR0712", "BG Generic home, second floor"},
	{"AR0713", "BG Generic home, ground floor"},
	{"AR0714", "BG Generic home, second floor"},
	{"AR0715", "BG Nadine's home, ground floor"},
	{"AR0716", "BG Nadine's home, second floor"},
	{"AR0717", "BG Generic home, ground floor"},
	{"AR0718", "BG Generic home, second floor"},
	{"AR0719", "BG Felonius Gist's home"},
	{"AR0720", "BG Drakon Tavern"},
	{"AR0721", "BG Warehouse full of rabid chickens"},
	{"AR0722", "BG Generic home, ground floor"},
	{"AR0723", "BG Generic home, second floor"},
	{"AR0724", "BG Marketplace tent (gambling)"},
	{"AR0725", "BG Marketplace tent (gambling)"},
	{"AR0726", "BG Diviner's marketplace tent"},
	{"AR0800", "BG E Baldur's Gate (Sorcerous Sundries, Elfsong Tavern)"},
	{"AR0801", "BG Generic home, ground floor"},
	{"AR0802", "BG Generic home, second floor"},
	{"AR0803", "BG Maltz's Weapon Shop, ground floor"},
	{"AR0804", "BG Maltz's Weapon Shop, second floor"},
	{"AR0805", "BG Arkion's home, ground floor"},
	{"AR0806", "BG Arkion's home, second floor"},
	{"AR0807", "BG Generic inn, ground floor"},
	{"AR0808", "BG Generic inn, second floor"},
	{"AR0809", "BG Silence's store"},
	{"AR0810", "BG Luck Aello's store"},
	{"AR0811", "BG Generic home, ground floor"},
	{"AR0812", "BG Generic home, second floor"},
	{"AR0813", "BG Nemphre's home, ground floor"},
	{"AR0814", "BG Nemphre's home, second floor"},
	{"AR0900", "BG Wyrm's Crossing (bridge to BG, Tenya, Quayle)"},
	{"AR0901", "BG Tenya's home"},
	{"AR1000", "BG Ulgoth's Beard (Shandalar, Ike, Mendas)"},
	{"AR1001", "BG Ulgoth Beard's Inn (Hurgan Stoneblade)"},
	{"AR1002", "BG Aec'Letec cult building, basement (Aec'Letec)"},
	{"AR1003", "BG Aec'Letec cult building, ground floor"},
	{"AR1004", "BG Mendas's home"},
	{"AR1005", "BG Therella's home"},
	{"AR1006", "BG Generic home"},
	{"AR1007", "BG Generic home"},
	{"AR1008", "BG Ice island, exterior"},
	{"AR1009", "BG Ice island, dungeon"},
	{"AR1010", "BG Ice island, unused exit area"},
	{"AR1100", "BG SW Baldur's Gate (Flaming Fist HQ, Merchant League, Seven Suns)"},
	{"AR1101", "BG Generic home, ground floor (thieves Wiven, Dirk, Meakin and Sath)"},
	{"AR1102", "BG Generic home, second floor"},
	{"AR1103", "BG Generic home, ground floor"},
	{"AR1104", "BG Generic home, second floor"},
	{"AR1105", "BG Generic home, ground floor"},
	{"AR1106", "BG Generic home, second floor"},
	{"AR1107", "BG Generic home, ground floor"},
	{"AR1108", "BG Generic home, second floor"},
	{"AR1109", "BG Generic tavern, ground floor (Phandalyn)"},
	{"AR1110", "BG Generic tavern, second floor"},
	{"AR1111", "BG Sunin's home"},
	{"AR1112", "BG Generic weapons store"},
	{"AR1113", "BG Ye Olde Inn, ground floor (green slimes, AKA Slime Inn)"},
	{"AR1114", "BG Ye Olde Inn, second floor (green slimes, AKA Slime Inn)"},
	{"AR1115", "BG Generic potions store"},
	{"AR1116", "BG Generic weapons store"},
	{"AR1117", "BG Generic potions store"},
	{"AR1200", "BG S Baldur's Gate (docks, Iron Throne, Low Lantern, Umberlee temple)"},
	{"AR1201", "BG Generic home, ground floor (ogre mages)"},
	{"AR1202", "BG Generic home, second floor"},
	{"AR1203", "BG Generic home, ground floor"},
	{"AR1204", "BG Generic home, second floor"},
	{"AR1205", "BG Generic home, ground floor"},
	{"AR1206", "BG Generic home, second floor"},
	{"AR1207", "BG Warehouse (loose basilisk)"},
	{"AR1208", "BG Warehouse (Noralee)"},
	{"AR1209", "BG Generic home, ground floor (Larriaz the Sirine)"},
	{"AR1210", "BG Generic home, second floor"},
	{"AR1211", "BG Ghorak's home, ground floor"},
	{"AR1212", "BG Ghorak's home, second floor"},
	{"AR1213", "BG Cordyr's home, ground floor"},
	{"AR1214", "BG Cordyr's home, second floor"},
	{"AR1215", "BG Jopalin's Tavern"},
	{"AR1300", "BG SE Baldur's Gate (Blade and Stars)"},
	{"AR1301", "BG Warehouse"},
	{"AR1302", "BG Well-Adjusted Al's General Store"},
	{"AR1303", "BG Warehouse (Nadarin)"},
	{"AR1304", "BG Generic home, ground floor"},
	{"AR1305", "BG Generic home, second floor"},
	{"AR1306", "BG Generic inn, ground floor (Euric)"},
	{"AR1307", "BG Generic inn, second floor (Sanadal Gwist)"},
	{"AR1308", "BG Generic home, ground floor"},
	{"AR1309", "BG Generic home, second floor"},
	{"AR1310", "BG Generic home, ground floor"},
	{"AR1311", "BG Generic home, second floor"},
	{"AR1312", "BG Gantolandan's home, ground floor"},
	{"AR1313", "BG Gantolandan's home, second floor"},
	{"AR1314", "BG Generic home, ground floor"},
	{"AR1315", "BG Generic home, second floor"},
	{"AR1316", "BG Generic home, ground floor (thieves Taxek and Michael)"},
	{"AR1317", "BG Generic home, second floor"},
	{"AR1320", "BG Generic store"},
	{"AR1400", "BG Fishing village (Ajantis, farmer Brun, Gerde, lots of ankhegs)"},
	{"AR1401", "BG Ankheg pit"},
	{"AR1402", "BG Fisherman's home"},
	{"AR1403", "BG Fisherman's home"},
	{"AR1404", "BG Brun's home"},
	{"AR1500", "BG Balduran's Isle, north (AKA Werewolf Isle)"},
	{"AR1501", "BG Balduran's ship, ground floor"},
	{"AR1502", "BG Balduran's ship, second floor"},
	{"AR1503", "BG Balduran's ship, third floor"},
	{"AR1504", "BG Balduran's ship, fourth floor (Karoug)"},
	{"AR1505", "BG Dradeel's home"},
	{"AR1600", "BG Cloakwood, third main area (shadow druids, Eldoth, Faldorn)"},
	{"AR1601", "BG Tree house, ground floor"},
	{"AR1602", "BG Tree house, second floor (Amarande)"},
	{"AR1603", "BG Baby wyvern cave (Peter of the North)"},
	{"AR1700", "BG Cloakwood, fourth main area (wyverns)"},
	{"AR1800", "BG Cloakwood mines, exterior"},
	{"AR1801", "BG Cloakwood mines, first subterranean level (river plug)"},
	{"AR1802", "BG Cloakwood mines, third subterranean level (Natasha, ogre mage)"},
	{"AR1803", "BG Cloakwood mines, fourth subterranean level (Davaeorn, Stephan)"},
	{"AR1804", "BG Cloakwood mines, second subterranean level (Yeslick, Hareishan)"},
	{"AR1805", "BG Cloakwood mines, barracks ground floor"},
	{"AR1806", "BG Cloakwood mines, barracks second floor"},
	{"AR1807", "BG Cloakwood mines, elevator"},
	{"AR1808", "BG Cloakwood mines, storehouse"},
	{"AR1809", "BG Cloakwood mines, shed leading to elevator"},
	{"AR1900", "BG Bandit Camp"},
	{"AR1901", "BG Bandit Camp, main tent (Raemon, Venkt, Hakt, Britik)"},
	{"AR1902", "BG Bandit Camp, tent (Ardenor Crush)"},
	{"AR1903", "BG Bandit Camp, cave (Garclax)"},
	{"AR1904", "BG Bandit Camp, tent (Tersus)"},
	{"AR1905", "BG Bandit Camp, tent (Knott)"},
	{"AR1906", "BG Bandit Camp, tent"},
	{"AR1907", "BG Bandit Camp, tent (Taugosz Khosann)"},
	{"AR2000", "BG Balduran's Isle, south (AKA Werewolf Isle, Delainy/Durlyle)"},
	{"AR2001", "BG Generic hut"},
	{"AR2002", "BG Main hut (Kaishas Gan, Tailas)"},
	{"AR2003", "BG Generic hut"},
	{"AR2004", "BG Generic hut"},
	{"AR2005", "BG Generic hut"},
	{"AR2006", "BG Generic hut"},
	{"AR2007", "BG Taloun's hut"},
	{"AR2008", "BG Generic hut"},
	{"AR2009", "BG Generic hut"},
	{"AR2010", "BG Generic hut"},
	{"AR2011", "BG Generic hut"},
	{"AR2012", "BG Werewolf caverns"},
	{"AR2100", "BG Cloakwood, second main area (spider nest, Centeol)"},
	{"AR2101", "BG Spider nest (Centeol)"},
	{"AR2200", "BG Cloakwood, first main area (Aldeth Sashenstar, Seniyad, Coran)"},
	{"AR2215", "BG Hunting lodge"},
	{"AR2300", "BG Friendly Arm Inn, exterior"},
	{"AR2301", "BG Friendly Arm Inn, ground floor (Bentley Mirrorshade, Khalid, Jaheira)"},
	{"AR2302", "BG Friendly Arm Inn, second floor (Unshey)"},
	{"AR2303", "BG Friendly Arm Inn, third floor (Landrin, Golden Pantaloons)"},
	{"AR2304", "BG Friendly Arm Inn, Temple of Wisdom (Gellana Mirrorshade)"},
	{"AR2305", "BG Friendly Arm Inn, generic home"},
	{"AR2306", "BG Friendly Arm Inn, Joia's home"},
	{"AR2400", "BG Peldvale (Viconia, Raiken)"},
	{"AR2600", "BG Candlekeep (prologue), exterior"},
	{"AR2602", "BG Candlekeep (prologue), Priest's Quarters (Shank)"},
	{"AR2605", "BG Candlekeep (prologue), infirmary"},
	{"AR2606", "BG Candlekeep (prologue), storehouse"},
	{"AR2607", "BG Candlekeep (prologue), bunkhouse (Carbos)"},
	{"AR2608", "BG Candlekeep Citadel, ground floor (Karan)"},
	{"AR2609", "BG Candlekeep Citadel, second floor (Koveras)"},
	{"AR2610", "BG Candlekeep Citadel, third floor (Rieltar, Brunos Costak, Tuth and Kestor)"},
	{"AR2611", "BG Candlekeep Citadel, fourth floor (Shistal)"},
	{"AR2612", "BG Candlekeep Citadel, fifth floor (Gorion's old room)"},
	{"AR2613", "BG Candlekeep Catacombs, entrance area"},
	{"AR2614", "BG Candlekeep Citadel, sixth floor (Ulraunt, Tethtoril)"},
	{"AR2615", "BG Candlekeep Catacombs, first level"},
	{"AR2616", "BG Candlekeep (prologue), Inn ground floor"},
	{"AR2617", "BG Candlekeep (prologue), Inn second floor"},
	{"AR2618", "BG Candlekeep (prologue), barracks"},
	{"AR2619", "BG Candlekeep Catacombs, second level"},
	{"AR2626", "BG Candlekeep (chapter 6), exterior"},
	{"AR2627", "BG Candlekeep (chapter 6), Priest's Quarters"},
	{"AR2628", "BG Candlekeep (chapter 6), storehouse"},
	{"AR2629", "BG Candlekeep (chapter 6), Inn ground floor"},
	{"AR2630", "BG Candlekeep (chapter 6), Inn second floor"},
	{"AR2631", "BG Candlekeep (chapter 6), barracks"},
	{"AR2632", "BG Candlekeep (chapter 6), bunkhouse"},
	{"AR2633", "BG Candlekeep (chapter 6), infirmary"},
	{"AR2643", "BG Candlekeep (prologue), warehouse (Obe's party combat training)"},
	{"AR2700", "BG Lion's Way (E of Candlekeep, Gorion's ambush, Imoen, Xzar, Montaron)"},
	{"AR2800", "BG Coast Way (S of Friendly Arm Inn, destroyed caravan)"},
	{"AR2900", "BG Larswood (Teven, Osmadi, Corsone)"},
	{"AR3000", "BG Spider Wood (E of Larswood, Thayvian Red Wizards)"},
	{"AR3100", "BG Shipwreck's Coast (S of Candlekeep, Shoal, Droth, Mad Arcand, Surgeon)"},
	{"AR3200", "BG High Hedge, exterior (Kivan)"},
	{"AR3201", "BG High Hedge, generic house"},
	{"AR3202", "BG High Hedge, interior (Thalantyr)"},
	{"AR3300", "BG Beregost (Garrick, Jovial Juggler, Feldepost's Inn, Burning Wizard, Red Sheaf))"},
	{"AR3301", "BG Thunderhammer Smithy (Taerom Fuiruim)"},
	{"AR3302", "BG Generic home"},
	{"AR3303", "BG Red Sheaf, second floor"},
	{"AR3304", "BG Jovial Juggler, ground floor (Bjornin, Gurke)"},
	{"AR3305", "BG Jovial Juggler, second floor front (Oogie)"},
	{"AR3306", "BG Jovial Juggler, second floor rear"},
	{"AR3307", "BG Burning Wizard, ground floor (Zhurlong)"},
	{"AR3308", "BG Burning Wizard, second floor"},
	{"AR3309", "BG Generic home, ground floor"},
	{"AR3310", "BG Generic home, second floor"},
	{"AR3311", "BG Generic home, ground floor"},
	{"AR3312", "BG Generic home, second floor"},
	{"AR3313", "BG Mirianne's home, ground floor"},
	{"AR3314", "BG Mirianne's home, second floor"},
	{"AR3315", "BG Landrin's home (spiders)"},
	{"AR3316", "BG Generic home"},
	{"AR3317", "BG Borland's home"},
	{"AR3318", "BG Generic home"},
	{"AR3319", "BG Galteran's home"},
	{"AR3320", "BG Travenhurst Manor, ground floor"},
	{"AR3321", "BG Travenhurst Manor, second floor"},
	{"AR3322", "BG Travenhurst Manor, Servants' Quarters"},
	{"AR3323", "BG Generic home, ground floor"},
	{"AR3324", "BG Generic home, second floor"},
	{"AR3325", "BG Generic home, second floor"},
	{"AR3326", "BG Generic home, ground floor"},
	{"AR3327", "BG Generic home, ground floor"},
	{"AR3328", "BG Generic home, second floor"},
	{"AR3329", "BG Generic home, second floor"},
	{"AR3330", "BG Generic home, ground floor"},
	{"AR3331", "BG Generic home, ground floor (Colquatle)"},
	{"AR3332", "BG Generic home, second floor"},
	{"AR3333", "BG Firebeard Elvenhair's home, ground floor"},
	{"AR3334", "BG Firebeard Elvenhair's home, second floor"},
	{"AR3335", "BG Generic home, ground floor"},
	{"AR3336", "BG Generic home, second floor"},
	{"AR3337", "BG Generic home, second floor"},
	{"AR3338", "BG Generic home, ground floor"},
	{"AR3339", "BG Generic home, ground floor"},
	{"AR3340", "BG Generic home, second floor"},
	{"AR3341", "BG Generic home, ground floor"},
	{"AR3342", "BG Generic home, second floor"},
	{"AR3343", "BG Generic home"},
	{"AR3344", "BG Generic home"},
	{"AR3345", "BG Generic home, ground floor"},
	{"AR3346", "BG Generic home, second floor"},
	{"AR3347", "BG Generic home, ground floor"},
	{"AR3348", "BG Generic home, second floor"},
	{"AR3349", "BG Generic home, ground floor"},
	{"AR3350", "BG Generic home, second floor"},
	{"AR3351", "BG Feldepost's Inn, ground floor (Marl)"},
	{"AR3352", "BG Feldepost's Inn, second floor (Algernon)"},
	{"AR3353", "BG Generic store (Kagain)"},
	{"AR3354", "BG Generic home"},
	{"AR3355", "BG Generic home, ground floor"},
	{"AR3356", "BG Generic home, second floor"},
	{"AR3357", "BG Red Sheaf, ground floor (Perdue)"},
	{"AR3400", "BG Beregost Temple, exterior (Cattack)"},
	{"AR3401", "BG Beregost Temple, vestibule"},
	{"AR3402", "BG Beregost Temple, interior (AKA Song of the Morning, Keldath Ormlyr)"},
	{"AR3500", "BG Mutamin's Garden (Shar-Teel, Mutamin, Korax, basilisks, Tamah)"},
	{"AR3600", "BG Seawatcher - Lighthouse (Safana, Ardrouine, Sil)"},
	{"AR3601", "BG Black Alaric's cave (flesh golems)"},
	{"AR3700", "BG Red Canyons (Bassilus, Melicamp)"},
	{"AR3800", "BG South Beregost Road"},
	{"AR3802", "BG Generic cave"},
	{"AR3900", "BG Ulcaster School, exterior (Ulcaster, Icharyd)"},
	{"AR3901", "BG Ulcaster School, dungeon"},
	{"AR4000", "BG Gullykin, exterior"},
	{"AR4001", "BG Jenkal's home, ground floor"},
	{"AR4002", "BG Jenkal's home, second floor"},
	{"AR4003", "BG Temple of Yondalla, ground floor"},
	{"AR4004", "BG Temple of Yondalla, basement"},
	{"AR4005", "BG Generic home, ground floor"},
	{"AR4006", "BG Generic home, basement"},
	{"AR4007", "BG Generic home, ground floor"},
	{"AR4008", "BG Generic home, basement"},
	{"AR4009", "BG Generic home, ground floor"},
	{"AR4010", "BG Generic home, basement"},
	{"AR4011", "BG Generic home, ground floor"},
	{"AR4012", "BG Generic home, basement"},
	{"AR4013", "BG Generic home, ground floor"},
	{"AR4014", "BG Generic home, basement"},
	{"AR4100", "BG Archaeological Site, exterior (Brage, Charleston Nib, Doomsayer)"},
	{"AR4101", "BG Archaeological Site, interior tomb"},
	{"AR4200", "BG Fisherman's Lake (Drizzt. Bjornin's half-ogres)"},
	{"AR4300", "BG North Nashkel Road (N of Nashkel)"},
	{"AR4400", "BG Lonely Peaks (Hulrik and Arabelle, Sarhedra, Arghain)"},
	{"AR4401", "BG Generic cave (ettercaps)"},
	{"AR4500", "BG Firewine Bridge (Kahrk, Carsa, Poe, Bentan, Melium)"},
	{"AR4501", "BG Wyvern cave"},
	{"AR4600", "BG Bear River (N of Gnoll Stronghold, Larel, Nevill, Jared)"},
	{"AR4700", "BG Xvart Village (Nexlit, Ursa, Borda)"},
	{"AR4701", "BG Generic cave (cave bear)"},
	{"AR4800", "BG Nashkel (Minsc, Edwin, Berrun Ghastkill, Belching Dragon, Temple of Helm)"},
	{"AR4801", "BG Nashkel Inn"},
	{"AR4802", "BG Temple of Helm (Nalin)"},
	{"AR4803", "BG Nashkel Store"},
	{"AR4804", "BG Nashkel Manor, ground floor"},
	{"AR4805", "BG Nashkel Manor, second floor (Samantha)"},
	{"AR4806", "BG Joseph's home"},
	{"AR4807", "BG Generic farmhouse"},
	{"AR4808", "BG Generic home"},
	{"AR4809", "BG Belching Dragon Tavern (Volo)"},
	{"AR4810", "BG Nashkel barracks"},
	{"AR4900", "BG Nashkel Carnival (Branwen, Great Gazib)"},
	{"AR4901", "BG Small carnival tent (armor merchant)"},
	{"AR4902", "BG Small carnival tent (black lotus)"},
	{"AR4903", "BG Large carnival tent (Vitiare)"},
	{"AR4904", "BG Large carnival tent (gambling)"},
	{"AR4905", "BG Small carnival tent (rare potions merchant)"},
	{"AR4906", "BG Small carnival tent (Zordral and Bentha)"},
	{"AR4907", "BG Small carnival tent (magic items merchant)"},
	{"AR4908", "BG Small carnival tent (melee weapons merchant)"},
	{"AR4909", "BG Small carnival tent (ranged weapons merchant)"},
	{"AR5000", "BG Valley of the Tombs (Nashkel mines exit, Narcillicus, Hentold)"},
	{"AR5001", "BG Tombs"},
	{"AR5100", "BG Gnoll Stronghold (Dynaheir)"},
	{"AR5101", "BG Generic cave (xvarts)"},
	{"AR5102", "BG Generic cave (Tome of Leadership and Influence)"},
	{"AR5103", "BG Generic cave (cariron crawlers)"},
	{"AR5200", "BG Dryad Falls (Cloudpeak Dryad, Drienne, Ingot, Krumm, Caldo)"},
	{"AR5201", "BG Firewine Ruins (Lendarn, ogre mage, undead knights)"},
	{"AR5202", "BG Generic cave"},
	{"AR5300", "BG Fire Leaf Forest (S of Nashkel, Albert, Rufie, Vax, Sendai)"},
	{"AR5400", "BG Nashkel Mines, exterior (Prism)"},
	{"AR5401", "BG Nashkel Mines, first subterranean level (Dink)"},
	{"AR5402", "BG Nashkel Mines, second subterranean level (Kylee, Beldin)"},
	{"AR5403", "BG Nashkel Mines, third subterranean level (Joseph)"},
	{"AR5404", "BG Nashkel Mines, fourth subterranean level"},
	{"AR5405", "BG Nashkel Mines, Mulahey's lair (Xan, Mulahey)"},
	{"AR5406", "BG Mine storehouse"},
	{"AR5500", "BG Gibberling Mountains (Samuel, Hafiz)"},
	{"AR5506", "BG Candlekeep Caves (Diarmid, Prat, Sakul, Tam, Bor)"},
	{"AR5600", "BG Random encounter area"},
	{"AR5601", "BG Random encounter area"},
	{"AR5700", "BG Random encounter area"},
	{"AR5701", "BG Random encounter area"},
	{"AR5800", "BG Random encounter area"},
	{"AR5801", "BG Random encounter area"},
	{"AR5900", "BG Random encounter area"},
	{"AR5901", "BG Random encounter area"},
	{"AR6000", "BG Random encounter area"},
	{"AR6001", "BG Random encounter area"},
	{"AR6100", "BG Random encounter area"},
	{"OH1000", "BG Dorn - Random Encounter Area"},
	{"OH2000", "BG Neera - Adoy's Enclave, exterior"},
	{"OH2010", "BG Neera - Adoy's Enclave, interior"},
	{"OH3000", "BG Rasaad - Dark Moon temple, exterior"},
	{"OH3010", "BG Rasaad - Dark Moon temple, interior"},
	{"OH3020", "BG Rasaad - Dark Moon temple, interior"},
	{"OH3100", "BG Rasaad - Dark Moon temple, interior"},
	{"OH1000", "BG Dorn - Random Encounter Area"},
	{"OH2000", "BG Neera - Adoy's Enclave, exterior"},
	{"OH2010", "BG Neera - Adoy's Enclave, interior"},
	{"OH3000", "BG Rasaad - Dark Moon temple, exterior"},
	{"OH3010", "BG Rasaad - Dark Moon temple, interior"},
	{"OH3020", "BG Rasaad - Dark Moon temple, interior"},
	{"OH3100", "BG Rasaad - Dark Moon temple, interior"},
}
cheatAreasArena = {
	{"OH9310", "Les Fosses Noires : Arène 1"},
	{"OH9350", "Les Fosses Noires : Arène 2"},
	{"OH9360", "Les Fosses Noires : Hall"},
}
cheatAreasTutorial = {
	{"TU0015", "Baldur's Gate Estate (Tutorial starts here)"},
	{"TU0016", "Baldur's Gate Estate (Tutorial area)"},
	{"TU0017", "Baldur's Gate Estate (Tutorial area)"},
	{"TU0018", "Baldur's Gate Estate Cellar (Tutorial area)"}
}
cheatAreasExpansion = {
	{"BD0010", "SoD Ducal Palace City Exterior"},
	{"BD0020", "SoD Sorcerous/Elf Song City Exterior"},
	{"BD0030", "SoD Flaming Fist City Exterior"},
	{"BD0040", "SoD Three Kegs City Exterior"},
	{"BD0050", "SoD Iron Throne City Exterior"},
	{"BD0060", "SoD Random Area - Cave Entrance"},
	{"BD0061", "SoD Random Area - Cave Interior from BD0060"},
	{"BD0062", "SoD Random Area - Cave Pool from BD0061"},
	{"BD0063", "SoD Random Area - Canyon Ambush"},
	{"BD0064", "SoD Random Area - Forest Paths"},
	{"BD0065", "SoD Random Area - Wilderness Open Area"},
	{"BD0066", "SoD Random Area - Wilderness Hole to BD0067"},
	{"BD0067", "SoD Random Area - Cave Interior from BD0066"},
	{"BD0070", "SoD The Scrying Pool - The Hooded Man Cutscene"},
	{"BD0071", "SoD The Scrying Pool - Caelar Cutscene"},
	{"BD0100", "SoD Ducal Palace, Second Floor"},
	{"BD0101", "SoD Ducal Palace, Leaving BG"},
	{"BD0102", "SoD Ducal Palace, First Floor"},
	{"BD0103", "SoD Ducal Palace, Third Floor"},
	{"BD0104", "SoD Flaming Fist HQ"},
	{"BD0105", "SoD Flaming Fist HQ, Basement"},
	{"BD0106", "SoD Three Old Kegs, First Floor"},
	{"BD0107", "SoD Three Old Kegs, Second Floor"},
	{"BD0108", "SoD Three Old Kegs, Third Floor"},
	{"BD0109", "SoD Elfsong Tavern, First Floor"},
	{"BD0110", "SoD Elfsong Tavern, Second Floor"},
	{"BD0111", "SoD Iron Throne Floor, First Floor"},
	{"BD0112", "SoD Baldur's Gate East"},
	{"BD0113", "SoD Underground Cavern Wyrms"},
	{"BD0114", "SoD Spider Cave"},
	{"BD0115", "SoD Vampire Cavern"},
	{"BD0116", "SoD Ducal Palace, Basement"},
	{"BD0117", "SoD Iron Throne, Basement"},
	{"BD0118", "SoD The Scrying Pool - Imoen Cutscene"},
	{"BD0120", "SoD Tomb Safehouse, First Floor"},
	{"BD0121", "SoD Sorcerous Sundries, First Floor"},
	{"BD0122", "SoD Sorcerous Sundries, Second Floor"},
	{"BD0130", "SoD Tomb Safehouse, Second Floor"},
	{"BD1000", "SoD Coast Way Crossing"},
	{"BD1010", "SoD Cave (generic)"},
	{"BD1100", "SoD The Dig"},
	{"BD1200", "SoD Lich Outpost"},
	{"BD2000", "SoD Boareskyr Bridge & Bridgefort"},
	{"BD2010", "SoD Cave (generic)"},
	{"BD2100", "SoD Bridgefort Interior"},
	{"BD3000", "SoD Allied Siege Camp"},
	{"BD4000", "SoD Dragonspear Castle, Exterior"},
	{"BD4100", "SoD Dragonspear Castle Keep, First Floor"},
	{"BD4300", "SoD Dragonspear Castle Basement"},
	{"BD4400", "SoD Avernus"},
	{"BD4500", "SoD Avernus Bridge"},
	{"BD4600", "SoD Avernus Interior"},
	{"BD4601", "SoD Avernus Elevator"},
	{"BD4700", "SoD Avernus Roof"},
	{"BD5000", "SoD Underground River Entrance"},
	{"BD5100", "SoD Underground River"},
	{"BD5110", "SoD Ettin Ghost Cave"},
	{"BD5200", "SoD The Warrens"},
	{"BD5300", "SoD Kanaglym"},
	{"BD6000", "SoD Abandoned Sewers & Caverns"},
	{"BD6200", "SoD Sewers Exit"},
	{"BD6100", "SoD The Ambush"},
	{"BD7000", "SoD Coast Way Forest"},
	{"BD7100", "SoD Troll Forest"},
	{"BD7110", "SoD Troll Cave"},
	{"BD7200", "SoD Forest of Wyrms"},
	{"BD7210", "SoD Wyrm Cave"},
	{"BD7220", "SoD Bugbear Stronghold"},
	{"BD7230", "SoD Temple of Cyric"},
	{"BD7300", "SoD Dead Man's Pass"},
	{"BD7310", "SoD Hidden Cellar/Treasure Stash"},
	{"BD7400", "SoD Bloodbark Grove"},
	{"BD7410", "SoD Vampire Hideout"},
}